_includes/head.html, _posts/2016-11-18-marketplace-roundtable.md, _posts/2016-11-22-how-the-bom-put-users-needs-first.md
The og-image is a temporary fix. Given the current mix of hero-images being half jekyll-assets, and half not, it was tough to fix it for all cases, so have added a temp front matter tag `og-image`. After resolving the hero-image issue, should remove it.
=> Update opengraph tags

Gemfile, Gemfile.lock, Rakefile, _config.yml, config.ru, manifest.yml
The static buildpack relies on 'bundle exec jekyll build' having been run before the 'cf push'. This commit changes to use the ruby build pack, so we can build the site as part of the assets pipeline. The files are then served in a puma webserver.
This means [QA Fire](https://qafire.apps.staging.digital.gov.au/4) can now be used.
=> Add support for running jekyll in cloudfoundry

_assets/scss/partials/_homepage.scss, _includes/breadcrumb.html, _layouts/home.html, pages/blog/index.html
Removes Author's names, and adds blog/news tag under each post.
Also fixes a bug with the display of li separators.
Closes  #168 
Closes #93
=> Change post list on home page

.gitignore, .pa11yci, README.md, _assets/scss/main.scss, _config.yml, _includes/header.html, _includes/search.html, _layouts/home.html, bin/cideploy.sh, bin/ciprepare.sh, bin/ciserve.sh, bin/citest.sh, circle.yml, google7a46798bcc50a03a.html, pa11y-sitemap.xml, pages/blog/index.html, pages/footer-links/signup.html, pages/standard/guides/gov-au-guides.md, pages/talent.html
Adds [pa11y-ci](https://github.com/pa11y/ci) to `citest.sh`.
CI starts up a background webserver in `ciserve.sh` for pa11y-ci to test against.
The existing `/sitemap.xml` created by jekyll-sitemap contains all the pdfs in the site, however pa11y-ci [raises an error](https://github.com/pa11y/ci/issues/10) when checking these. To solve this I have added a `/pa11y-sitemap.xml` which is just used by pa11y. When this issue is fixed in pa11y-ci this should be removed.
Have also fixed all the issues identified by pa11y so that the tests pass.
Closes #129
=> Add pa11y to CI tests

bin/ciserve.sh
=> Set pa11y serve destination to a temp dir so we avoid clobbering _site

bin/ciprepare.sh, bin/ciserve.sh, bin/citest.sh
In `citest.sh` I wanted to run htmlproofer before pa11y, as it is faster and so will find the things most likely to break sooner.
pa11y requires the webserver to be running before it starts. This is started in the background in parallel by circleci. I have moved the wait for the webserver later in the script as well so we're not waiting while we can do other work. We are using `set -x` (echo each line of the script), so this now means that every time we sleep a line is printed, which breaks [circleci timeouts](https://circleci.com/docs/configuration/#modifiers). Hence I've had to add a timeout.
I've done this with a simple loop counter.
=> Add timeout while waiting for webserver to start

_assets/scss/partials/_header.scss
When the site was being released, at the last minute I was having issues with the svg logo falling back to png for ie 8, so as a quick fix I changed to always use the png. This PR restores the svg logo for all browsers except for < ie 9 using the lt-ie9 class. I have tested that the png fallback works ok in ie8.
Closes #178
=> Change logo to svg with ie8 fallback to png

Gemfile, Gemfile.lock, _assets/scss/partials/_blog.scss, _assets/scss/partials/_homepage.scss, _config.yml, _includes/breadcrumb.html, _includes/post-list-item.html, _layouts/home.html, _layouts/post.html, _layouts/tag-archive.html, _posts/2016-08-29-digital-marketplace-beta.md, _posts/2016-10-21-marketplace-sharing-positive-feedback.md, _posts/2016-10-28-new-digital-agency-establishes-agenda.md, _posts/2016-11-09-marketplace-shaped-by-user-needs.md, _posts/2016-11-18-marketplace-roundtable.md, _posts/2016-11-22-how-the-bom-put-users-needs-first.md, _posts/2016-11-30-paul-shetler-resignation.md, _posts/2016-12-15-digital-steps-to-benefit-users.md, bin/cibuild.sh, pages/blog/dto-news/index.html, pages/blog/gov-au-blog/index.html, pages/blog/index.html, pages/news/index.html, pages/tags.html, pages/what-we-do/transformation-agenda/transformation-agenda.md
- Change from the manually created pages for each tag to [jekyll-assets](https://github.com/jekyll/jekyll-assets) so it is easier to manage tags.
- Tags are now visible on the post list pages and when viewing the post.
=> Change to jekyll-assets

_assets/js/assessment-tabs.js, _assets/scss/partials/_assessment-reports.scss, pages/standard/assessment-reports.md
I suggest reviewing the [files changed ignoring whitespace ?w=1](https://github.com/AusDTO/dta-website/pull/251/files?w=1)
Closes #147
=> Change assessment reports list from tabs to inline-links

pages/contact/contact.md, pages/contact/events.html
Closes #105.
We host the form in jekyll, but the form action is to [script.google.com]. After submitting, there is a very simple thankyou page: 
For testing, if JEKYLL_ENV != production then `?test=1` is appended to the path and the email is not sent:
=> Add event contact form

pages/standard/common-solutions.md
As the GovShare is discontinued, links should be removed.
=> Remove broken link for discontinued GovShare

bin/buildrc, bin/checkexternal.sh, bin/cibuild.sh, bin/ciserve.sh, bin/citest.sh
After circleci builds each branch, it publishes the artefacts in a static web server. With these tweaks, assets will work when viewing these artefacts. This means that links to the pages on circle can be shared to help people preview the content within the context of the site. 
e.g. https://1166-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/index.html
Unfortunately, clicking on links to other parts of the site do not work, as [the circle web server does not automatically append /index.html](https://discuss.circleci.com/t/circle-artifacts-com-not-using-index-html/320) like the site expects (as it does when served by nginx) However being able to share a link to the built content on circle may still be useful.
Closes #268
=> Fix previewing changes in circle artefacts

_assets/scss/partials/_annual-report.scss, _assets/scss/partials/_tables.scss, _includes/annual-report/3.1-appropriations-tables.html, pages/who-we-are/corporate/annual-report-15-16/02-program-performance.md, pages/who-we-are/corporate/annual-report-15-16/03-org-performance.md, pages/who-we-are/corporate/annual-report-15-16/04-financial-statement.md, pages/who-we-are/corporate/annual-report-15-16/05-references.md, pages/who-we-are/corporate/annual-report-15-16/text-versions/4-appropriations-table.md
Breaking out some of the changes for the annual report in #243.
Wraps all tables except for Table 1 in a div with overflow:auto so the tables are still readable at mobile, albeit with scrolling.
H/T to @TrebBrennan.
I recommend ignoring whitespace when reviewing this PR -  [?w=1 link](https://github.com/AusDTO/dta-website/pull/328/files?w=1)
Preview links:
[Section 2](https://1401-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/who-we-are/corporate/annual-report/2015-16/2-program-performance/index.html)
[Section 3](https://1401-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/who-we-are/corporate/annual-report/2015-16/3-organisational-performance/index.html)
[Section 4](https://1401-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/who-we-are …
=> Add horizontal scroll to all non-responsive tables in the annual report

bin/buildrc, bin/cideploy.sh
Previously, if you tried to add a branch with a slash e.g. feature/foo it would get deployed to cloud foundry at dta-website-feature/foo.apps. etc and not work. With this fix, the branch name is passed through `basename`, so the app name becomes dta-website-foo.apps. etc
=> Fix so branches with a / can be continuously deployed

_assets/scss/main.scss, _assets/scss/partials/_homepage.scss, _assets/scss/partials/_latest-post-list.scss, _assets/scss/partials/_transformation-agenda.scss, _includes/latest-post-list-item.html, _includes/post-list-item.html, _layouts/home.html, _layouts/tag-archive.html, pages/blog/all-posts/index.html, pages/blog/index.html, pages/news/all/index.html, pages/news/index.html, pages/what-we-do/transformation-agenda/transformation-agenda.md
This PR addresses issue [2] from the accessibility review - two adjacent links to the same destination was redundant and confusing for screen reader users. 
I have:
- merged the two links into one on the home page and /blog/
- removed the link on the image for the /blog/all and /news lists
Preview links:
Home page https://1467-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/index.html
/blogs https://1467-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/blog/index.html
/blog/all-posts - https://1467-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/blog/all-posts/index.html
Closes #275
=> Remove duplicate adjacent links

_includes/latest-post-list-item.html
Currently the homepage has some layout issues on IE11:
This PR fixes the overflow.
https://1620-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/index.html
=> Add div around <a> to fix in IE11

_assets/js/search.js.liquid
The class `.has-value` is now checked and added on load, as well as whenever the search text changes.
Closes #315
=> Trigger site search text change on load

_assets/js/vendor/ui-kit.js
This PR hotfixes ui-kit.js to add the `aria-expanded` to the site and local nav menu buttons, as recommended in the accessibility review.
Preview links:
https://1678-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/what-we-do/index.html
Closes #283
=> Add aria-expanded to the responsive nav

_assets/js/vendor/mc-validate.js, pages/footer-links/signup.html
This PR addresses issue #295 from the accessibility review.
Validation in the sign-up form is handled by the mailchimp supplied mc-validate.js.
This issue has been reported upstream to mailchimp. 
For now I have changed so this file is served locally, and hotfixed setting `aria-describedby` when the input fields are invalid as recommended in the accessibility review:
You can see just the hotfix in this commit: https://github.com/AusDTO/dta-website/pull/381/commits/da0da9e06cc750c62e70096b187aec5de5e0ca38 
Preview link: https://1687-71211972-gh.circle-artifacts.com/0/home/ubuntu/dta-website/_site/signup/index.html
Closes #295
=> Add aria-describedby attribute for validation error labels on sign-up form

bin/buildrc, bin/cideploy.sh, bin/ciprepare.sh, manifest.yml
- Circle deploys the PR to https://pr-426-dta-website.apps.staging.digital.gov.au
- QAFire will not deploy, but will still update PR status with the link to the above.
- When the PR is closed, QA Fire will then delete the above app.
Note that since the deploy requires the PR number, Circle has been changed to only build when a PR is created.
=> Add support for qafire

_assets/scss/partials/_list-vertical.scss
Fixes #431.
Adding a max-width 100% to the image div fixes the issue on firefox. Have tested with browserstack to make sure it hasn't broken any others.
=> Fix firefox bug with homepage thumbnails

bin/cideploy.sh, nginx-production.conf, nginx.conf
This PR is an attempt to improve the caching performance on production from #370.
I have increased the caching of html content to 5 minutes. I'm hoping this will give cloud front enough time to propagate new pages so we don't get 404's. If this doesn't work we might have to look again into purging cloud front each deploy.
To prevent this new caching time being a nuisance in staging, I've added a separate nginx conf file `ngix-production.conf` to be used in production which has the previous caching settings. This is renamed to `nginx.conf` by the `cideploy.sh` when required. In non-production deploys a different nginx.conf will be used which does not have caching.
=> Increase html caching time

_posts/2017-07-19-tech-behind-dta-website.md
From a marketing and SEO perspective, even though we are not yet using it on the site we should link to the current website of the product.
=> Change uikit link

nginx-production.conf
It's safest to remove this entirely - in production this redirection should be handled by the CDN
=> Remove http to https redirection

pages/what-we-do/policies-and-programs/secure-cloud.md
This commit adds a redirect from `/secure-cloud/` to `/what-we-do/policies-and-programs/secure-cloud/`.
=> Secure cloud redirect
