AusDTO/dta-website

_includes/head.html, _posts/2016-11-18-marketplace-roundtable.md, _posts/2016-11-22-how-the-bom-put-users-needs-first.md
=> Fix opengraph meta tags

_posts/2016-11-18-marketplace-roundtable.md
Oops I missed one of the images
=> Sharpen images

_assets/scss/partials/_assessment-reports.scss, _layouts/assessment-report.html, _layouts/home.html, pages/blog/index.html, pages/standard/digital-service-standard.md
Fixes #148 
Fixes #210 
Fixes #211
=> Accessibility fixes

_includes/footer.html, bin/cideploy.sh, pages/who-we-are/corporate/freedom-of-information/our-reports-and-responses-to-parliament.md, pages/who-we-are/corporate/jobs/before-you-apply.md, pages/who-we-are/corporate/jobs/information-pack.md, pages/who-we-are/corporate/jobs/jobs.md
- Jobs page
- Information Pack becomes Before you apply
- Added CEO position
=> Deploy to production

_assets/js/vendor/ui-kit.js, _assets/scss/main.scss, _assets/scss/partials/_blog.scss, _assets/scss/partials/_embed.scss, _includes/transcripts/transcript-discovery.md, _posts/2016-12-15-digital-steps-to-benefit-users.md, pages/standard/discovery.md
Quick fix for #242.
A change to ui-kit.js had to be applied to make the accordion collapse and expand function work. I will submit the fix upstream.
=> Change Read Transcripts to heading blocks

_assets/scss/partials/_recruiterbox.scss
=> Fix jobs hover double-underline

_posts/2017-01-19-ab-coding.md
=> Adds abbrs to HABTM and defines first PR abbr.

_includes/footer.html, _includes/signup.html, pages/footer-links/signup.html
Closes #312 
Ready to merge, but waiting until mailchimp side of things is ready
=> Add signup categories

_assets/scss/main.scss, _assets/scss/partials/_annual-report.scss, _assets/scss/partials/_tables.scss, pages/who-we-are/corporate/annual-report-15-16/02-program-performance.md
Table 1 in the Annual Report would suit a css responsive table approach so it's still readable on mobile. I've used the approach from https://css-tricks.com/responsive-data-tables/
=> Add css responsive table

_posts/2017-02-20-making-source-code-open.md
A reader on twitter ( @aussielunix )pointed out that the blog post didn't talk about open source licenses. Ive added some text and linked the choose a license website.
=> Add information about open source licenses

pages/who-we-are/corporate/contracts.md, pages/who-we-are/corporate/freedom-of-information/index.md, pages/who-we-are/corporate/public-interest-disclosure.md
Added local nav on some corporate pages.
=> Update with local navigation

_includes/search.html
Remove additional link url from search page.
It resolves the issue #292
=> Remove redundant link

pages/standard/guides/branding.md, pages/standard/guides/inclusive-services.md, pages/standard/guides/making-content-accessible.md, pages/standard/guides/online-writing.md, pages/standard/guides/testing-web-accessibility.md
=> Redirected to updated page

nginx-production.conf, nginx.conf
As requested in ticket: https://digital89.zendesk.com/agent/tickets/177
=> Add header to prevent iframing from other sites

_includes/survey.html, _layouts/base.html
Just a small addition to the base.html layout to include the survey.html. The pop-up only works after 90 seconds, and once it has popped it won't pop again unless you clean out Survey Monkey cookies. Best bet is to turn off cookies while testing and run in incognito mode, though you'll still have to wait 90 seconds.
=> Added Survey Monkey pop-up code to base layout.

_includes/head.html
Updated twitter:card setting in _includes/head.html to "summary_large_image".
=> Changed twitter card layout.

_includes/survey.html, _layouts/base.html
Deleted _includes/survey.html and removed jekyll code from _layouts/base.html.
=> Removing survey.

pages/what-we-do/policies-and-programs/ict-procurement/ict-capped-term-value-policy.md
=> Added ICT contract capped term and value policy.

.gitignore
Reverts AusDTO/dta-website#634
=> Revert "Updated gitignore to prevent the robots file from being moved between…"

robots.txt
Reverts AusDTO/dta-website#633
=> Revert "Updated robots.txt for staging."

README.md, bin/buildrc, manifest-develop.yml, manifest-production.yml, manifest.yml
The staging address will be changing soon.
Change the value of  `CF_STAGING_API` in circle first, and then merge this PR.
=> New staging addres

bin/cideploy.sh, bin/ciprepare.sh, manifest-develop.yml, manifest-production.yml, manifest.yml
(Haven't tested yet, so might be best to wait until tomorrow)
It will also mean we'll need to delete the old blue green apps afterwards as a once off.
=> Switch to using autopilot plugin, with our mods

_assessment-reports/alpha-special-access-scheme.md
Reverts AusDTO/dta-website#794
=> Revert "Revert "TGA Assessment report""

pages/what-we-do/policies-and-programs/starting-a-digital-career/apprenticeship.md, pages/what-we-do/policies-and-programs/starting-a-digital-career/cadetship.md
Added ASD to Cadets and Apprenticeships.
=> Updated agencies

_assets/scss/partials/_typography.scss
This commit adds some helper classes to enable images to be floated left or right with appropriate margins.
=> Image alignment

pages/what-we-do/policies-and-programs/starting-a-digital-career/apprenticeship.md
This commit adds a link to the jobs page which seems to have dropped off at some point.
=> Fixed link to jobs page

_posts/2018-06-12-have-your-say-on-our-draft-digital-panel-policy.md, _posts/2018-06-12-next-steps-for-our-procurement-framework.md
=> Link Fixes

pages/what-we-do/partnerships/communities.md
Added open data communities to the Communities of practices page
=> Added open data communities

_posts/2018-06-12-next-steps-for-our-procurement-framework.md, pages/what-we-do/partnerships/communities.md
Added open data communities to communities of practice page
=>  Added open data communities

pages/what-we-do/partnerships/communities.md
on the Communities of practice page
Reformatted bullet points into paragraphs
=> Reformatted bullet points into paragraphs

_posts/2018-07-05-a-coordinated-approach-to-buying-it-ibm.md
This PR includes a IBM news item
=> IBM news item

pages/what-we-do/policies-and-programs/women-in-it.md
Reverts AusDTO/dta-website#973
=> Revert "Updating Women in IT content to match beta site"

pages/what-we-do/platforms/marketplace.md
Removed words referring to beta.
=> Digital Marketplace update
